import { ImageSourcePropType } from 'react-native';

export const CATEGORY_LOGO: Record<number, ImageSourcePropType> = {
  9: require('assets/images/general-knowledge.webp'),
  10: require('assets/images/books.webp'),
  11: require('assets/images/film.webp'),
  12: require('assets/images/music.webp'),
  13: require('assets/images/musicals-theatres.webp'),
  14: require('assets/images/television.webp'),
  15: require('assets/images/video-games.webp'),
  16: require('assets/images/board-games.webp'),
  17: require('assets/images/science-nature.webp'),
  18: require('assets/images/science-computers.webp'),
  19: require('assets/images/science-mathematics.webp'),
  20: require('assets/images/mythology.webp'),
  21: require('assets/images/sports.webp'),
  22: require('assets/images/geography.webp'),
  23: require('assets/images/history.webp'),
  24: require('assets/images/politics.webp'),
  25: require('assets/images/art.webp'),
  26: require('assets/images/celebrities.webp'),
  27: require('assets/images/animals.webp'),
  28: require('assets/images/vehicles.webp'),
  29: require('assets/images/comics.webp'),
  30: require('assets/images/science-gadgets.webp'),
  31: require('assets/images/japanese-anime-manga.webp'),
  32: require('assets/images/cartoon-animations.webp'),
};
